recipe: default.v1

assistant_id: 20250120-010028-poky-scotia

language: en

version: "3.1"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer    
- name: LexicalSyntacticFeaturizer    
- name: CountVectorsFeaturizer    
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier    
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper   
  case_sensitive: false
- name: RegexEntityExtractor    
  use_lookup_tables: true
  use_regexes: true
  use_word_boundaries: true
- name: ResponseSelector    
  epochs: 100
- name: FallbackClassifier    
  threshold: 0.4
  ambiguities_threshold: 0.1

policies:
- name: MemoizationPolicy    
- name: RulePolicy    
  core_fallback_threshold: 0.4
  core_fallback_action_name: "utter_clarify"
- name: UnexpecTEDIntentPolicy    
  max_history: 5
  epochs: 100
- name: TEDPolicy    
  max_history: 10
  epochs: 100